export const dragonsContants = {
  SET_ALL_DRAGONS: 'SET_ALL_DRAGONS',
  GET_DRAGON_BY_ID: 'GET_DRAGON_BY_ID',
  EDIT_DRAGON_BY_ID: 'EDIT_DRAGON_BY_ID',
  SET_DRAGON: 'SET_BOOK',
  DELETE_DRAGON: 'DELETE_DRAGON',
}